# Bug: `Сюда впишите название бага`

## Summary

Короткое описание ошибки

## Environment

Ссылка на билд или коммит, версия ПО и всего окружения

## Steps to reproduce

Полный перечень шагов для воспроизведения

## Expected result

Какой результат должен был быть без ошибки

## Actual result

Какой результат получился на самом деле
