name: 🐛 Bug Report
description: Сообщить об ошибке в проекте
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: input
    id: summary
    attributes:
      label: Краткое описание
      placeholder: "Например: Кнопка 'Сохранить' не работает"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Шаги, чтобы воспроизвести ошибку
      description: Напиши пошагово, как воспроизвести баг
      placeholder: |
        1. Перейти на страницу входа  
        2. Ввести данные  
        3. Нажать "Войти"  
        4. Получить ошибку
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Что должно было произойти
      placeholder: "Например: Должна была открыться домашняя страница"

  - type: textarea
    id: actual
    attributes:
      label: Что произошло на самом деле
      placeholder: "Например: Появилось сообщение об ошибке '401 Unauthorized'"

  - type: textarea
    id: environment
    attributes:
      label: Информация о среде
      placeholder: "Например: Chrome 115 / macOS / версия 1.2.3"

  - type: textarea
    id: screenshots
    attributes:
      label: Скриншоты или логи (если есть)
      description: Прикрепи скриншоты или вставь текст ошибки
